server:
  port: 8089
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    hikari:
      pool-name: HikariCP-1
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 2000
      idle-timeout: 10000
      max-lifetime: 30000
  application:
    name: Learning-Spring-Data-JPA-Service

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update